<?php 

/**
 * Implementation of hook_wysiwyg_plugin()
 * 
 * Adds extended_valid_elements array to TinyMCE so it's possible for staff
 * with correct permissions to add iframe's to content especially Google
 * maps. This permission should only be granted to trusted accounts 
 * 
 * @param $editor
 * @param $version
 * @return array Formatted for TinyMCE Wysiwyg plugin
 */

function tinymce_extended_wysiwyg_plugin($editor, $version) {
  switch($editor) {
    case 'tinymce':
      return array(
        'iframe' => array(
          'extensions' => array('iframe' => t('Iframe Fix')),
          'extended_valid_elements' => array('iframe[src|width|height|frameborder|scrolling]'),
          'load' => FALSE,
          'internal' => TRUE,
          ),
      );
  }
}

/**
 * Implementation of hook_help()
 * @param $path
 * @param $arg
 * @return unknown_type
 */
function tinymce_extended_help($path, $arg) {
  if ($path == 'admin/help#tinymce_extended') {
    return t('Enables iframe use in TinyMCE editor using Wysiwyg module.');
  }
}